### ISSUE TITLE
Upload plugin to NPM

### ISSUE THREAD

**Issue by giovannidias1** [khanhna/ckeditor5-image-via-url#1]
Please, it would be possible to upload the plugin in NPM as this would avoid messing with the node_modules folder.

**Comment by khanhna** [comment]
I'm sorry to say that based on the traffic and users responds... it is unworthy for me to upload this.
Not to mention this can be somehow miss-understood, and causing conflict in the case that CKEditor team want to add the official version of this feature. (including the parameters for secure of course).

But believe me... this one is good and easy enough to include it in your build with just a few minutes.

P/s: I'm not a Js-Dev actually.... and hofully someone can make a serious plugin for this feature to save us all.
